### PR TITLE
default values may be problematic in some usages

### PR DESCRIPTION
**Pull request by boucadair**

### CODE REVIEW

**Comment by QiufangMa** [comment]
These are the nodes that should be mandatory to have values, otherwise, the recurrence behavior is unclear.
e.g., when it is a "daily" recurrence, it is unknown whether it is everyday or every N days.
we could have "everyday" by default (default interval value is 1), but could also be "every three days" by explicitly setting the "interval" value as 3.

**Comment by boucadair** [comment]
> These are the nodes that should be mandatory to have values, otherwise, the recurrence behavior is unclear.

I think we just need to indicate the default value as part of the description not as a yang statement. The narrative text can explain the implication of not supplying interval, for example.

The concern I'm seeing with having a default is that we we define some profile that uses the grouping, and the same grouping is used by a router (for example) in addition to the profile, the default value will override what is in the profile.

**Comment by QiufangMa** [comment]
> The concern I'm seeing with having a default is that if we define some profile that uses the grouping, and the same grouping is used by a router (for example) in addition to the profile, the default value will override what is in the profile.

Is the profile intended to use another value for default? I am assuming the default value defined here is applicable for all cases, but i also agree no one could stop a default value being refined when "uses" the groupings...

**Comment by QiufangMa** [comment]
> However, the key comment is that we should be careful to not impact how the grps will be reused.

Sure. While I see no difference to describe the default value in the desc compared with using the "default" statement, if two consumers have different understandings of the default behavior (e.g., the profile refine the description with another default  value). 
Maybe define as "mandatory true"?

**Comment by boucadair** [comment]
I would soften the constraints and have in the description as much guidance. So, no mandatory/default is still my preference here.

**Comment by QiufangMa** [comment]
> I would soften the constraints and have in the description as much guidance.

okay, let's proceed with this way for now, and see if there is any objection from others in the future.

**Comment by boucadair** [comment]
> > I would soften the constraints and have in the description as much guidance.
> 
> okay, let's proceed with this way for now, and see if there is any objection from others in the future.

Thanks.

**Pull request merged**
